server.port=8081

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/moodfit_db
spring.datasource.username=moodfit
spring.datasource.password=moodfit_secret
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Swagger
springdoc.swagger-ui.path=/api
